### ISSUE TITLE
multiple billboards

### ISSUE THREAD

**Issue by xiaoouwang** [daschaa/billboard#1]
Hey!

Just discover your app, so much fun!

Is it possible to have multiple billboards? One is certainly not enough xDDD

**Comment by daschaa** [comment]
@xiaoouwang Thanks for your comment. I appreciate that you like the app ❤️
Multiple billboards are a great idea. I will put it on the to-do list. If you want to, feel free to open a pull request. ☺️

**Comment by daschaa** [comment]
Hi, I decided to not implement this feature in the near future. Still thank you for the issue!
