### ISSUE TITLE
App icon not showing properly

### ISSUE THREAD

**Issue by Hovera** [daschaa/billboard#10]
Hi, first of all, thanks so much for developing such a handy app! I use it to display daily affirmations. However, there seems to be no icon in launchpad (app menu). It's the empty grid template icon. I don't know if there should be though. MacOS version Ventura 13.1. Thanks.
<img width="235" alt="Screenshot 2023-02-02 at 21 20 49" src="https://user-images.githubusercontent.com/11656118/216505559-07b24fa0-1d2e-485e-bba5-ee79f5d536f6.png">

**Comment by daschaa** [comment]
@Hovera Hi! Thanks for opening the issue. I really appreciate that you like the app.
Unfortunately I really don't have an icon for the app due to my lack of design skills. Also I did not find a good open source icon, but maybe in the future.

**Comment by Hovera** [comment]
> @Hovera Hi! Thanks for opening the issue. I really appreciate that you like the app. Unfortunately I really don't have an icon for the app due to my lack of design skills. Also I did not find a good open source icon, but maybe in the future.

Thank you. It's not a problem at all and let's wait if anyone has a good idea about it!
